/**
 * pdf-thumbnail-wasm
 * High-performance PDF thumbnail generation for browsers, Node.js, and Edge environments
 */

export type {
  ImageFormat,
  ThumbnailOptions,
  BatchOptions,
  SizeSpec,
  PageInfo,
  StreamResult,
} from './types';

// The actual implementation will be generated by wasm-bindgen
// This file serves as a re-export point and can include additional helpers

/**
 * Helper function to create a Blob URL from image data
 * @param data - Image data as Uint8Array
 * @param mimeType - MIME type (e.g., 'image/jpeg')
 * @returns Blob URL that can be used as img.src
 */
export function createBlobUrl(data: Uint8Array, mimeType: string): string {
  const blob = new Blob([data], { type: mimeType });
  return URL.createObjectURL(blob);
}

/**
 * Helper function to download image data as a file
 * @param data - Image data as Uint8Array
 * @param filename - Filename for download
 * @param mimeType - MIME type
 */
export function downloadImage(data: Uint8Array, filename: string, mimeType: string): void {
  const url = createBlobUrl(data, mimeType);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Helper function to convert image data to base64 data URL
 * @param data - Image data as Uint8Array
 * @param mimeType - MIME type
 * @returns Base64 data URL
 */
export function toDataUrl(data: Uint8Array, mimeType: string): string {
  const base64 = btoa(String.fromCharCode(...data));
  return `data:${mimeType};base64,${base64}`;
}

/**
 * Get MIME type for image format
 */
export function getMimeType(format: 'jpeg' | 'png' | 'webp'): string {
  const types = {
    jpeg: 'image/jpeg',
    png: 'image/png',
    webp: 'image/webp',
  };
  return types[format];
}

/**
 * Get file extension for image format
 */
export function getExtension(format: 'jpeg' | 'png' | 'webp'): string {
  const extensions = {
    jpeg: 'jpg',
    png: 'png',
    webp: 'webp',
  };
  return extensions[format];
}
